013 Refactor + rename repo (#13)

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,21 +1,40 @@
 #!/bin/bash
+
 set -e
 
-echo "BEGIN INSTALL OF MANDATORY PACKAGES"
+if ! xcode-select -p &> /dev/null; then
+    echo "Command Line Tools are not installed. Installing..."
+    xcode-select --install
+else
+    echo "Command Line Tools are already installed."
+fi
+
 echo "---------------------------------"
 
-install_package() {
-  local package=$1
+if ! command -v brew &> /dev/null; then
+    echo "Homebrew is not installed. Installing..."
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+    echo "Homebrew is now installed and ready to use. Checking for updates..."
+    brew update
+else
+    echo "Homebrew is already installed. Updating..."
+    brew update
+fi
 
-  echo "Checking if $package is installed..."
+echo "---------------------------------"
 
-  if ! brew list --formula | grep -q "^$package$"; then
-    echo "$package is not installed. Installing..."
-    brew install "$package" >/dev/null 2>&1
-    echo "$package installation complete."
+install_formula() {
+  local formula=$1
+
+  echo "Checking if $formula is installed..."
+
+  if ! brew list --formula | grep -q "^$formula$"; then
+    echo "$formula is not installed. Installing..."
+    brew install "$formula" >/dev/null 2>&1
+    echo "$formula installation complete."
   else
-      echo "$package is already installed. Upgrading..."
-      brew upgrade "$package" >/dev/null 2>&1
+      echo "$formula is already installed. Upgrading..."
+      brew upgrade "$formula" >/dev/null 2>&1
   fi
 
   echo "---------------------------------"
@@ -38,26 +57,8 @@ install_cask() {
   echo "---------------------------------"
 }
 
-if ! xcode-select -p &> /dev/null; then
-    echo "Command Line Tools are not installed. Installing..."
-    xcode-select --install
-else
-    echo "Command Line Tools are already installed."
-fi
-echo "---------------------------------"
-
-if ! command -v brew &> /dev/null; then
-    echo "Homebrew is not installed. Installing..."
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-    echo "Homebrew is now installed and ready to use. Checking for updates..."
-    brew update
-else
-    echo "Homebrew is already installed. Updating..."
-    brew update
-fi
-echo "---------------------------------"
-
-PACKAGES=(
+formulae=(
+  "awscli"
   "azure-cli"
   "Azure/kubelogin/kubelogin"
   "detect-secrets"
@@ -70,21 +71,21 @@ PACKAGES=(
   "snyk"
 )
 
-CASKS=(
-  "docker"
+casks=(
+  "docker-desktop"
   "dotnet-sdk"
   "visual-studio-code"
 )
 
-for package in "${PACKAGES[@]}"; do
-  install_package "$package"
+for formula in "${FORMULAE[@]}"; do
+  install_package "$formula"
   
   # Special handling for Snyk CLI
-  if [ "$package" == "snyk" ]; then
+  if [ "$formula" == "snyk" ]; then
       brew tap snyk/tap
   fi
 
-  if [ "$package" = "openjdk" ]; then
+  if [ "$formula" = "openjdk" ]; then
     echo "To complete OpenJDK installation, please do the following:"
     echo "If using Zsh: echo 'export PATH=\"/opt/homebrew/opt/openjdk/bin:\$PATH\"' >> ~/.zshrc"
     echo "If using Bash: echo 'export PATH=\"/opt/homebrew/opt/openjdk/bin:\$PATH\"' >> ~/.bashrc"
@@ -102,8 +103,6 @@ brew outdated || true
 echo "Updating outdated packages..."
 echo "All packages installed via Homebrew are up to date."
 
-echo "Required packages/software for FFC development have now been installed."
-echo "DISCLAIMER: packges/software not covered in this scripts includes NVM (Node Version Manager) and neostandard"
-echo "Please refer to the FFC Development Guide for instructions: https://github.com/DEFRA/ffc-development-guide/blob/main/docs/local-development-setup/index.md"
-
-echo "END"
+echo "Required packages for FCP development have now been installed."
+echo "DISCLAIMER: Packages not covered in this scripts includes NVM (Node Version Manager) and neostandard,"
+echo "            please refer to the FFC Development Guide for instructions: https://github.com/DEFRA/ffc-development-guide/blob/main/docs/local-development-setup/index.md"
